#!/bin/bash
./node_modules/.bin/watchify -dv \
    -t [ envify --NODE_ENV development ] \
    -t babelify \
    --extension=".jsx" \
    --extension=".js" \
    -e client/src/initialize.js \
    -o 'client/public/scripts/bundle.js' \
    -x underscore \
    -x react/addons \
    -x superagent \
    -x node-polyglot \
    -x moment \
    -x classnames \
    -x react-router \
    -x react-redux \
    -x redux \
    -x immutable \
    -x reselect
